### ISSUE TITLE
No effect on wifi

### ISSUE THREAD

**Issue by 61Halim** [jakeajames/RealCC#1]
I install it, and no effect on wifi icon on cc. It is normal, how it works?

**Comment by jakeajames** [comment]
It should disable wifi when you tap on it

**Comment by 61Halim** [comment]
No wifi doesn´t work, if I click on wifi toogle  it disconnected from my wifi but it doesn´t disabled.
Bluetooth works, if I click the toogle it disabled bluetooth

**Comment by Packetfahrer** [comment]
@61Halim can you Tell me the Title in your Setting´s for Wifi or your Language ?

**Comment by 61Halim** [comment]
The title is WLAN my language is German

**Comment by Packetfahrer** [comment]
Ok then wait a little bit, this is Fixed in my Pull request. 
Auf deutsch warte bis er meinen Fix implementiert hat. :)

**Comment by 61Halim** [comment]
Ah ok thanks, then I will wait for the update

**Comment by Namouk** [comment]
@jakeajames  @Packetfahrer 

Your last update (0.0.1-14) still doesn't work for phones displaying WLAN instead of wifi in the settings.

To fix it you need to change 

`localizedStringForKey:@"CONTROL_CENTER_STATUS_WIFI_NAME"`

to

`localizedStringForKey:@"CONTROL_CENTER_STATUS_WLAN_NAME"`

I can confirm it works just as intended.

Thanks for this great tweak!

**Comment by 61Halim** [comment]
@Namouk how and which file to change?

**Comment by Namouk** [comment]
@61Halim 

If you don't know, you better wait a little until they update it.

**Comment by 61Halim** [comment]
Edit: It works!
